version: "3"

services:
  ds-yandex:
    container_name: ds-yandex
    command: npm run start:prod
    env_file: /home/cwash/apps/ds-mobile/config/yandex/.env.production
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "10m"
    restart: unless-stopped
  ds-yandex-rp:
    container_name: ds-yandex-rp
    hostname: ds-yandex-rp
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf.prod:/etc/nginx/conf.d/default.conf
      - /home/cwash/apps/ds-mobile/logs/ya/nginx:/var/log/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  bull-queue:
    container_name: bull-queue
networks:
  default:
    external:
      name: ds-mobile-external