version: '3'

services:
  ds-yandex:
    build: ./
    depends_on:
      - bull-queue
    environment:
      REDIS_HOST: bull-queue
    restart: unless-stopped
  bull-queue:
    image: redis:7.0-alpine
    command: redis-server --appendonly yes --replica-read-only no
    restart: unless-stopped
    ports:
      - "6379:6379"
  ds-yandex-rp:
    image: nginx:stable-alpine