version: "3"

services:
  ds-yandex:
    command: npm run start:dev
    env_file:
      - ./.env.development
    volumes:
      - ./ds-yandex/src:/usr/app/src
  ds-yandex-rp:
    ports:
      - "5061:5061"
    volumes:
      - ./nginx/default.conf.dev:/etc/nginx/conf.d/default.conf